leftnav:
- identifier: f1dee39d-0c72-485c-a3f6-e9f7dd6e85f8
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: d7b7e804-d8d2-4f8b-9d95-d4c568d245ef
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 4f45d5c4-5144-4091-a0a6-3080b6ce480f
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
